### ISSUE TITLE
Missing some icons

### ISSUE THREAD

**Issue by dipakparmar** [ecklf/react-native-heroicons#10]
Hi 👋,

Thanks for the awesome work creating and maintaining the react-native library for heroicons.  

Seems it is missing some icons; in my case, I was looking for the wallet icon, which is missing. Guessing you built the last package before tailwindlabs fixed the missing icons in their package. https://github.com/tailwindlabs/heroicons/pull/785 

Can you please rebuild the package with new updates so that it can fix?

Thanks ❤️

**Comment by ecklf** [comment]
Hey there, that looks correct. I just did a resync and published a new package.

**Comment by dipakparmar** [comment]
Working now. Thanks for fixing it. 😀
