### ISSUE TITLE
Crashes for all icons with the latest version of `react-native-svg`

### ISSUE THREAD

**Issue by tsheaff** [ecklf/react-native-heroicons#12]
Using `react-native-svg@12.3.0`, this package works great.

But if I upgrade to `react-native-svg@13.4.0`, I get the following error when using any components from the library:

<img width="564" alt="Screenshot 2022-11-22 at 11 08 12 AM" src="https://user-images.githubusercontent.com/1238684/203421644-691c214c-2449-4142-84c7-8958f45bc1d2.png">

**Comment by paulpopus** [comment]
Not experiencing this issue with `react-native-svg@13.4.0` and `react-native-heroicons@3.2.0`

**Comment by ecklf** [comment]
Hey, I've updated to the latest version of `svgr` and hope this will resolve this issue. Do you mind testing out via `npm i react-native-heroicons@@beta` and tell me if it resolves the issue?

**Comment by ShaneBurkhart** [comment]
adding the error message as text for search engines

JSON value { 2 } of type NSMutableArray cannot be converted to NSDictionary

thank you

**Comment by danieltott** [comment]
@ecklf That change fixed this issue for me - any way we could get a non-beta release going?

**Comment by ecklf** [comment]
@danieltott cool published a new version just now. Also making a new minor version adding the new micro icons as we speak.
