### ISSUE TITLE
Medium icon versions

### ISSUE THREAD

**Issue by Vanluren** [ecklf/react-native-heroicons#3]
Hey, this is an awesome repo! Many thanks.

Are there any plans to add the medium/non-solid versions of the icons?

**Comment by impulse** [comment]
> Hey, this is an awesome repo! Many thanks.
> 
> Are there any plans to add the medium/non-solid versions of the icons?
> 
> 

Already available suffixed with "Outline". Or do you mean something else?

https://www.github.com/impulse/react-native-heroicons/tree/master/src%2Ficons

**Comment by Vanluren** [comment]
Ah, awesome! If you allow pull requests, i would love to make this clear in the README 👍

**Comment by Vanluren** [comment]
Made a pull request with updates to the README: #4

**Comment by ecklf** [comment]
Merged in 035fc01210bcb034b7c2bb32c5a3c18c7fd1e628
