### ISSUE TITLE
strokeWidth prop

### ISSUE THREAD

**Issue by camillo18tre** [ecklf/react-native-heroicons#7]
Great work here!
It's there a way to set the strokeWidth prop?

thank you

**Comment by camillo18tre** [comment]
no one here?

**Comment by ecklf** [comment]
Hi @camillo18tre, this package aims to have feature parity with the official web packages of `@heroicons/react`. I don't plan on supporting this unless they do.

**Comment by n8udd** [comment]
For anyone coming across this...
It appears that simply setting `strokeWidth={X}` works fine.

````
<UsersIcon
  size="24"
  color="#60a5fa"
  fill="#fff"
  strokeWidth={4}
/>
````

Presumably because it's supported in `react-native-svg`.
