### ISSUE TITLE
Unable to use version 3.0.0

### ISSUE THREAD

**Issue by j3sch** [ecklf/react-native-heroicons#9]
Since upgrading to version 3.0.0 I get the following error:
I also tried it with a new project.

expo: ~46.0.9,
```
Exception thrown while executing UI block: -[__NSDictionaryM firstObject]: unrecognized selector sent to instance 0x60000118f060

__53-[ABI46_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    ABI46_0_0RCTUIManager.m:1202
__53-[ABI46_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.431
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim

0x0
```
![Simulator Screen Shot - iPhone 13 - 2022-08-28 at 14 39 19](https://user-images.githubusercontent.com/39447994/187074576-b4ecb3b0-86f8-4ebd-af56-af54b784757c.png)

**Comment by j3sch** [comment]
After downgrading

**Comment by ecklf** [comment]
@j3sch interesting, could you tell me which icon you used to produce this so I can have a look?

**Comment by mpandzo** [comment]
@ecklf I experienced the same thing (and used the same downgrade solution to get things working) with the PlusIcon class:

```
import { PlusIcon } from 'react-native-heroicons/mini';
```

and

```
export default function App() {
  return (
    <View>
      <PlusIcon />
    </View>
  );
}
```

**Comment by smoothwastaken** [comment]
Same issue, and this downgrade solution worked also on my side.
